### ISSUE TITLE
Player seed not found

### ISSUE THREAD

**Issue by wjm2038** [Earthcomputer/EnchantmentCracker#15] opened 2018-04-19 03:38 UTC
I follow the video and calculate 2 xp seeds, but when I was calculating player seed it says player seed not found. 
![image](https://user-images.githubusercontent.com/10401572/38970101-952d12a6-4361-11e8-9082-b614c6e19e3c.png)
here is the log
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/1926561/enchcracker.log)

**Comment by wjm2038** [comment] 2018-04-19 03:44
I set the language to Chinese, is that the reason?

**Comment by Earthcomputer** [comment] 2018-04-19 12:42
Dupe of #12. It's not due the language being set to Chinese, it's due to that combination of XP seeds being impossible to form a player seed. This means that there is either a bug in the XP seed cracker (unlikely since I haven't changed that part of the code since the initial release and it's worked for me and others every time), or you're doing something wrong.
If you are absolutely sure you are following all the instructions in the explanation video very precisely, including all the extra instructions in the video description, simply reply to this and I'll re-open this so we can investigate this further. In the mean time though, I'm going to close this issue.

**Closed by Earthcomputer** 2018-04-19 12:42 UTC
Labels: duplicate
