### ISSUE TITLE
i cant use 1.17

### ISSUE THREAD

**Issue by daangerd** [Earthcomputer/EnchantmentCracker#279] opened 2021-11-23 16:34 UTC
![Schermopname (4)](https://user-images.githubusercontent.com/94922013/143064999-7c15036c-f31e-41f9-8c87-11ec7e29ce3d.png)
i don't have the option for 1.17 although the version I downloaded says it does have the option for 1.17

**Comment by wagyourtail** [comment] 2021-11-23 17:46
Duplicate of #276, #277, please search for existing issues before creating a new one

**Closed** 2021-11-23 17:46 UTC
