### ISSUE TITLE
No 1.17 option

### ISSUE THREAD

**Issue by hotheadb1** [Earthcomputer/EnchantmentCracker#278] opened 2021-11-23 02:51 UTC
![Screenshot 2021-11-22 184734](https://user-images.githubusercontent.com/88118508/142964243-1159810e-62e1-40a3-8a3b-aecd1cc75b18.png)
As this image shows there is no 1.17 option 
I've tried the 1.16 and it doesn't work in 1.17

**Comment by Earthcomputer** [comment] 2021-11-23 10:19
Duplicate of #276, please search for existing issues before creating a new one

**Closed by Earthcomputer** 2021-11-23 10:19 UTC
