### ISSUE TITLE
Mac OS Native Library Loading Failure

### ISSUE THREAD

**Issue by thatonemurphy** [Earthcomputer/EnchantmentCracker#28] opened 2018-06-30 10:38 UTC
The title of this issue speaks for itself. Running ./enchcracker.sh in Terminal comes back with "./enchcracker.sh: No such file or directory"
[2018-06-30 05:34:50] [/INFO]: System details:
[2018-06-30 05:34:50] [/INFO]: OS = Mac OS X 10.13.5
[2018-06-30 05:34:50] [/INFO]: Arch (either OS/Java) = x86_64
[2018-06-30 05:34:50] [/INFO]: Java = 10.0.1
[2018-06-30 05:34:50] [/INFO]: Java arch = 64
[2018-06-30 05:34:50] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path: [/Users/thatonemurphy/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

Would really appreciate the help! My mind was blown that you were able to figure this out man <3

**Comment by Earthcomputer** [comment] 2018-07-16 23:59
Dupe of #13

**Closed by Earthcomputer** 2018-07-16 23:59 UTC
