### ISSUE TITLE
1.4.3 won't start

### ISSUE THREAD

**Issue by 576576** [Earthcomputer/EnchantmentCracker#104] opened 2019-08-14 12:17 UTC
I tried to cilck bin/enchcracker.bat to run 1.4.3, but no GUI were appeard,
the lib/enchcracker-1.4.3.jar either, but my java is already installed.

**Comment by Earthcomputer** [comment] 2019-08-14 12:18
Duplicate of #103

**Closed by Earthcomputer** 2019-08-14 12:18 UTC
