### ISSUE TITLE
Not working in snapshot versions

### ISSUE THREAD

**Issue by TheDarkAndroid** [Earthcomputer/EnchantmentCracker#152] opened 2020-04-10 07:30 UTC
I know this is probably to be expected but I didn't see an issue about this so I'll open one.

**Comment by TheDarkAndroid** [comment] 2020-04-10 07:30
Also I have no clue how to add labels

**Comment by Earthcomputer** [comment] 2020-04-10 13:38
Duplicate of #133, although the necessary changes for 1.16 so far have been implemented, and you can use it if you compile from source. I only create releases for full releases, and I explain the reasoning in the linked issue.

Adding labels is something most users don't have permission to do, sorry!

**Closed by Earthcomputer** 2020-04-10 13:38 UTC

**Comment by TheDarkAndroid** [comment] 2020-04-10 15:51
How can I compile from source?

**Comment by Earthcomputer** [comment] 2020-04-10 16:05
Follow the "building from source" section in the readme.

**Comment by TheDarkAndroid** [comment] 2020-04-10 16:55
![image](https://user-images.githubusercontent.com/20667076/79008028-c923dd80-7b5c-11ea-9118-af65ee0dfffe.png)
This is what happens

**Comment by Earthcomputer** [comment] 2020-04-10 17:11
Oh, right, I need to update gradle then. In the mean time, you can compile it with jdk8.

**Comment by TheDarkAndroid** [comment] 2020-04-10 19:42
I set the JAVA_HOME, but how do I compile?

**Comment by Earthcomputer** [comment] 2020-04-11 11:44
Just run `gradlew build`

**Comment by TheDarkAndroid** [comment] 2020-04-11 12:06
Again, the same "Could not determine java version from '14'" error

**Comment by Earthcomputer** [comment] 2020-04-11 13:10
Ah, sod it! I updated Gradle for you, so it should now recognize your Java 14 installation.
- Run `git pull` to get the up-to-date version of the repository.
- Try `gradlew build` again after that.

**Comment by TheDarkAndroid** [comment] 2020-04-11 13:44
Ok, I built it, thanks and sorry for bothering you

**Comment by TheDarkAndroid** [comment] 2020-04-11 14:52
Also, I've done this 3 times now, there's always something missing from what I've tried to enchant.

**Comment by TheDarkAndroid** [comment] 2020-04-11 15:05
In particular Looting and Sweeping Edge were missing on both of the 2 swords (1 netherite and 1 diamond) that I enchanted.

**Comment by Earthcomputer** [comment] 2020-04-11 15:42
It might be better to create a new issue to track that, and I will try and reproduce your issue, thanks

**Comment by Earthcomputer** [comment] 2020-04-11 18:18
@TheDarkAndroid you must have done something wrong. I just tried it out on the latest snapshot (20w15a), and succesfully enchanted both a netherite and diamond sword with looting 3, sweeping edge 3 and sharpness 4.

**Comment by TheDarkAndroid** [comment] 2020-04-11 18:27
Hmm, I'll have to try again
