### ISSUE TITLE
enhancement: add an option to ignore the player seed warning

### ISSUE THREAD

**Issue by buildartifacts** [Earthcomputer/EnchantmentCracker#198] opened 2020-08-24 21:44 UTC
Currently, if you try to calculate the requirements for enchants without a player seed, it gives a message that the player seed needs to be found first. It would be nice if it was possible to ignore the message and use a random player seed for testing (e.g. find best possible toolsmith pickaxe). Sorry if this was already posted I couldn't find it if it was.

**Comment by Earthcomputer** [comment] 2020-08-24 22:00
Duplicate of #97

**Closed by Earthcomputer** 2020-08-24 22:00 UTC
