### ISSUE TITLE
 Can't enchant a tool with 3 enchanments

### ISSUE THREAD

**Issue by galihcanfly** [Earthcomputer/EnchantmentCracker#92] opened 2019-08-02 13:09 UTC
Hey , i like your program ( really usefull! ) but  I can't enchant a tool with 3 enchantments as you did in the video , it is said impossible.

**Comment by Earthcomputer** [comment] 2019-08-02 14:10
Duplicate of #68

**Closed by Earthcomputer** 2019-08-02 14:10 UTC
