### ISSUE TITLE
Seems to always be IMPOSSIBLE with more than 2 enchantments in v1.14.2?

### ISSUE THREAD

**Issue by snakevil** [Earthcomputer/EnchantmentCracker#68] opened 2019-06-17 00:39 UTC
I tried over 3 times, find Player seed, set Item, and then add Enchantments.

It's going well with 1 or 2 Enchantments. But after I added the 3rd Enchantments, it always turned to IMPOSSIBLE. Whatever 1st and 2nd and 3rd Enchantments I had chosen.

Is it any restriction in 1.14.2? Or any issue about the toolkit?

**Comment by snakevil** [comment] 2019-06-23 02:24
something is wrong about armor enchanting. 

I've tried to enchant `diamond_boots` with `depth_strider` and `fire_protection` (only 2 enchantments could work). 

Either in local or in remote server, the results are the same `feather_falling 4` and `protection 3`.

**Comment by KokeCacao** [comment] 2019-06-24 11:12
for `diamond_sword`, you can have `looting 2`, `fire_aspect 1`, `sharpness 4`. Also, I tested and the input order of those enchantments seem to have some effect. This may not be expected by the user of this program.

**Comment by Earthcomputer** [comment] 2019-07-22 16:16
Enchanting was nerfed in 1.14 which was reverted in 1.14.3. It's probably due to that. A 1.14.3 version will be released soon. As for the other issue relating to ordering of enchanting, that shouldn't happen. Could you double check to confirm then create a separate issue for that?

**Closed by Earthcomputer** 2019-07-22 16:16 UTC

**Comment by KokeCacao** [comment] 2019-07-26 15:41
> Enchanting was nerfed in 1.14 which was reverted in 1.14.3. It's probably due to that. A 1.14.3 version will be released soon. As for the other issue relating to ordering of enchanting, that shouldn't happen. Could you double check to confirm then create a separate issue for that?

Sorry, It was probably my mistake since I can't reproduce it.
