### ISSUE TITLE
Crash: bad_alloc after reseting the cracker and adding info.

### ISSUE THREAD

**Issue by questforboobs** [Earthcomputer/EnchantmentCracker#32] opened 2018-07-29 23:54 UTC
[2018-07-29 20:46:10] [/INFO]: System details:
[2018-07-29 20:46:10] [/INFO]: OS = Windows 10 10.0
[2018-07-29 20:46:10] [/INFO]: Arch (either OS/Java) = amd64
[2018-07-29 20:46:10] [/INFO]: Java = 1.8.0_181
[2018-07-29 20:46:10] [/INFO]: Java arch = 64
[2018-07-29 20:49:54] [/INFO]: Added info, b = 15, s1 = 5, s2 = 9, s3 = 30
[2018-07-29 20:50:22] [/INFO]: Reduced possible seeds to 69206175
[2018-07-29 20:50:33] [/INFO]: Added info, b = 14, s1 = 7, s2 = 14, s3 = 28
[2018-07-29 20:50:34] [/INFO]: Reduced possible seeds to 877143
[2018-07-29 20:50:49] [/INFO]: Added info, b = 13, s1 = 4, s2 = 7, s3 = 26
[2018-07-29 20:50:49] [/INFO]: Reduced possible seeds to 14669
[2018-07-29 20:51:06] [/INFO]: Added info, b = 12, s1 = 6, s2 = 10, s3 = 24
[2018-07-29 20:51:06] [/INFO]: Reduced possible seeds to 273
[2018-07-29 20:51:33] [/INFO]: Added info, b = 11, s1 = 4, s2 = 11, s3 = 22
[2018-07-29 20:51:33] [/INFO]: Reduced possible seeds to 11
[2018-07-29 20:51:49] [/INFO]: Added info, b = 10, s1 = 6, s2 = 9, s3 = 20
[2018-07-29 20:51:49] [/INFO]: Reduced possible seeds to 1
[2018-07-29 20:52:10] [/INFO]: Reset the cracker
[2018-07-29 20:52:29] [/INFO]: Added info, b = 10, s1 = 5, s2 = 11, s3 = 20
[2018-07-29 20:53:09] [/SEVERE]: An unexpected error occurred
enchcracker.NativeException: std::bad_alloc: std::bad_alloc
	at enchcracker.NativeSingleSeedCracker.nfirstInput(Native Method)
	at enchcracker.NativeSingleSeedCracker.firstInput(NativeSingleSeedCracker.java:60)
	at enchcracker.EnchCrackerWindow$3.lambda$1(EnchCrackerWindow.java:237)
	at java.lang.Thread.run(Unknown Source)

**Comment by Earthcomputer** [comment] 2018-08-10 22:37
Dupe of #20

**Closed by Earthcomputer** 2018-08-10 22:37 UTC
