### ISSUE TITLE
How do I update to the 1.14 prerelease? 

### ISSUE THREAD

**Issue by forshale** [Earthcomputer/EnchantmentCracker#61] opened 2019-05-19 22:53 UTC
I saw the 1.14 files with the java and native things, however i cant figure out how to install them, help please?

**Comment by Earthcomputer** [comment] 2019-05-20 10:20
1.14 is not supported yet. That commit was *supposed* to make it work for 1.14, but it doesn't for some reason, that still needs to be looked into.

**Comment by Earthcomputer** [comment] 2019-05-20 10:21
Closing since it's a dupe of #55

**Closed by Earthcomputer** 2019-05-20 10:21 UTC
