### ISSUE TITLE
Can't seem to open enchcracker.bat, and enchcracker.jar doesn't work either.

### ISSUE THREAD

**Issue by NoFourRhythm** [Earthcomputer/EnchantmentCracker#27] opened 2018-06-13 03:05 UTC
on windows 10
[2018-06-13 11:02:46] [/INFO]: System details:
[2018-06-13 11:02:46] [/INFO]: OS = Windows 10 10.0
[2018-06-13 11:02:46] [/INFO]: Arch (either OS/Java) = x86
[2018-06-13 11:02:46] [/INFO]: Java = 1.8.0_171
[2018-06-13 11:02:46] [/INFO]: Java arch = 32
[2018-06-13 11:02:46] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: A:\Downloads Folder\enchcracker (1)\enchcracker\enchcracker.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

[2018-06-13 11:02:48] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacity(Unknown Source)
	at enchcracker.JavaSingleSeedCracker.initCracker(JavaSingleSeedCracker.java:39)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:108)

**Comment by Earthcomputer** [comment] 2018-06-14 21:32
Dupe of #20, look there for solutions

**Closed by Earthcomputer** 2018-06-14 21:32 UTC
